#!/bin/bash
# OpenClaw DR Installation Script
# Usage: ./install.sh [--local] [--clone] [--no-full-output] [--prefix DIR]
#   --local        Install from current directory (default)
#   --clone        Clone from remote repository
#   --no-full-output  Don't auto-cat report after completion (default: cat)
#   --prefix DIR   Install prefix (default: ~/bin)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"

# Default values
MODE="local"
FULL_OUTPUT="yes"
PREFIX="$HOME/bin"
INSTALL_DIR="$HOME/.local/share/openclaw-dr"

usage() {
    echo "OpenClaw DR Installation Script"
    echo ""
    echo "Usage: $0 [options]"
    echo ""
    echo "Options:"
    echo "  --local             Install from current directory (default)"
    echo "  --clone             Clone from GitHub to install directory"
    echo "  --no-full-output    Don't auto-cat report after completion"
    echo "  --prefix DIR        Install directory (default: ~/bin)"
    echo "  --help              Show this help"
    echo ""
    echo "Examples:"
    echo "  $0 --local                          # Install from current dir"
    echo "  $0 --clone                          # Clone from GitHub"
    echo "  $0 --clone --no-full-output        # Clone without auto output"
    echo "  $0 --prefix /usr/local/bin         # Custom prefix"
    exit 0
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --local)
            MODE="local"
            ;;
        --clone)
            MODE="clone"
            ;;
        --no-full-output)
            FULL_OUTPUT="no"
            ;;
        --prefix)
            PREFIX="$2"
            shift
            ;;
        --help|-h)
            usage
            ;;
        *)
            echo "Unknown option: $1"
            usage
            ;;
    esac
    shift
done

echo "=== OpenClaw DR Installation ==="
echo "Mode: $MODE"
echo "Prefix: $PREFIX"
echo "Full output: $FULL_OUTPUT"
echo ""

# Ensure prefix directory exists
mkdir -p "$PREFIX"

if [ "$MODE" = "clone" ]; then
    echo "Cloning repository to $INSTALL_DIR..."
    if [ -d "$INSTALL_DIR/.git" ]; then
        echo "Repository already exists, pulling latest..."
        (cd "$INSTALL_DIR" && git pull)
    else
        git clone https://github.com/p010-ai/openclaw-dr.git "$INSTALL_DIR" 2>/dev/null || \
        git clone https://github.com/p010-ogger/openclaw-dr.git "$INSTALL_DIR" 2>/dev/null || {
            echo "ERROR: Could not clone repository"
            echo "Please try --local mode or check your internet connection"
            exit 1
        }
    fi
    INSTALL_DIR_FOR_DR="$INSTALL_DIR/scripts"
else
    INSTALL_DIR_FOR_DR="$REPO_ROOT/scripts"
fi

# Create wrapper script
WRAPPER_PATH="$PREFIX/dr"

echo "Installing wrapper to $WRAPPER_PATH..."

cat > "$WRAPPER_PATH" << 'WRAPPER_EOF'
#!/bin/bash
# OpenClaw DR CLI Wrapper
# Auto-generated by install.sh

SCRIPT_NAME="$(basename "$0")"
INSTALL_DIR_FOR_DR="@@INSTALL_DIR_FOR_DR@@"
FULL_OUTPUT="@@FULL_OUTPUT@@"

# Run the actual script
"$INSTALL_DIR_FOR_DR/dr" "$@"
RC=$?

# Auto-cat report if enabled and successful
if [ "$FULL_OUTPUT" = "yes" ] && [ $RC -eq 0 ]; then
    RUNS_DIR="$("$INSTALL_DIR_FOR_DR/dr" --runs-dir 2>/dev/null | grep -oP 'runs[/\w]*' | head -1)"
    if [ -z "$RUNS_DIR" ]; then
        RUNS_DIR="./runs"
    fi

    # Find latest report by mtime (not relying on run_* prefix)
    LATEST_REPORT=$(ls -1t "$RUNS_DIR"/*/final/report.md 2>/dev/null | head -n 1)
    if [ -n "$LATEST_REPORT" ] && [ -f "$LATEST_REPORT" ]; then
        echo ""
        echo "=== Full Report ==="
        cat "$LATEST_REPORT"
        echo ""
        echo "Report saved to: $LATEST_REPORT"
    fi
fi

# Show verification info on exit(3)
if [ $RC -eq 3 ]; then
    RUNS_DIR="$("$INSTALL_DIR_FOR_DR/dr" --runs-dir 2>/dev/null | grep -oP 'runs[/\w]*' | head -1)"
    if [ -z "$RUNS_DIR" ]; then
        RUNS_DIR="./runs"
    fi

    # Find latest verification by mtime
    LATEST_VERIFY=$(ls -1t "$RUNS_DIR"/*/final/verification.md 2>/dev/null | head -n 1)
    if [ -n "$LATEST_VERIFY" ] && [ -f "$LATEST_VERIFY" ]; then
        echo ""
        echo "=== Verification Details ==="
        cat "$LATEST_VERIFY"
    fi
fi

exit $RC
WRAPPER_EOF

# Replace placeholders
sed -i '' "s|@@INSTALL_DIR_FOR_DR@@|$INSTALL_DIR_FOR_DR|g" "$WRAPPER_PATH"
sed -i '' "s|@@FULL_OUTPUT@@|$FULL_OUTPUT|g" "$WRAPPER_PATH"

chmod +x "$WRAPPER_PATH"

echo ""
echo "=== Installation Complete ==="
echo "dr installed to: $WRAPPER_PATH"
echo ""
echo "To use immediately, run:"
echo "  source ~/.bashrc  # or ~/.zshrc"
echo "  dr 'your topic'"
echo ""
echo "Optional: Enable /dr shortcut:"
echo "  $SCRIPT_DIR/enable_dr_slash.sh"
