#!/usr/bin/env python3
"""
Generate demo_run for Deep Research.

Creates a reproducible demo run at runs/demo_run/ with all expected artifacts.
Run this script to generate demo_run before release.
"""

import json
import os
from pathlib import Path
from datetime import datetime

SCRIPT_DIR = Path(__file__).parent
CLAWD_DIR = SCRIPT_DIR.parent
RUNS_DIR = CLAWD_DIR / "runs"
DEMO_RUN_DIR = RUNS_DIR / "demo_run"


def ensure_dir(path: Path) -> None:
    """Ensure directory exists."""
    path.mkdir(parents=True, exist_ok=True)


def create_clarify_json() -> None:
    """Create clarify.json with sample clarification."""
    data = {
        "status": "clarified",
        "questions": [
            "What specific topic would you like to research?",
            "What aspect or angle are you interested in?",
            "What is the purpose of this research?"
        ],
        "answers": ["climate change impact on agriculture", "global food security", "academic paper"],
        "failure_reason": None
    }
    path = DEMO_RUN_DIR / "clarify.json"
    with open(path, "w") as f:
        json.dump(data, f, indent=2)
    print(f"Created: {path}")


def create_paragraphs_jsonl() -> None:
    """Create paragraphs.jsonl with sample paragraphs."""
    paragraphs = [
        {"text": "Climate change significantly impacts agricultural productivity worldwide. Rising temperatures and changing precipitation patterns affect crop yields and growing seasons (C001)", "cite_ids": ["C001"]},
        {"text": "Global food security faces unprecedented challenges from climate-induced agricultural shifts. Studies show yield reductions of up to 30% in major crop-producing regions (C002)", "cite_ids": ["C002"]},
        {"text": "Adaptation strategies include developing heat-tolerant crop varieties, improving irrigation efficiency, and diversifying agricultural systems (C003)", "cite_ids": ["C003"]},
    ]
    path = DEMO_RUN_DIR / "drafts" / "paragraphs.jsonl"
    ensure_dir(path.parent)
    with open(path, "w") as f:
        for p in paragraphs:
            f.write(json.dumps(p) + "\n")
    print(f"Created: {path}")


def create_report_md() -> None:
    """Create sample report.md."""
    content = """# Research Report: Climate Change Impact on Agriculture

## Executive Summary

This report examines the multifaceted impacts of climate change on global agricultural systems and food security.

## Key Findings

### Impact on Crop Yields

Climate change significantly impacts agricultural productivity worldwide. Rising temperatures and changing precipitation patterns affect crop yields and growing seasons (C001).

### Food Security Challenges

Global food security faces unprecedented challenges from climate-induced agricultural shifts. Studies show yield reductions of up to 30% in major crop-producing regions (C002).

### Adaptation Strategies

Adaptation strategies include developing heat-tolerant crop varieties, improving irrigation efficiency, and diversifying agricultural systems (C003).

## Conclusion

Addressing climate change impacts on agriculture requires coordinated global action and innovative solutions.

---
*Generated by Deep Research MVP*
"""
    path = DEMO_RUN_DIR / "final" / "report.md"
    ensure_dir(path.parent)
    with open(path, "w") as f:
        f.write(content)
    print(f"Created: {path}")


def create_verification_md() -> None:
    """Create verification.md."""
    content = """# Verification Report

## Summary

| Metric | Value |
|--------|-------|
| Total Paragraphs | 3 |
| Paragraphs without Citation | 0 |
| Citations Found | 3 |
| Verification Status | PASSED |

## Details

### Citation Format Check

All paragraphs end with proper citations in (Cxxx) format.

### Paragraph Verification

- Paragraph 1: Has citation (C001) ✓
- Paragraph 2: Has citation (C002) ✓
- Paragraph 3: Has citation (C003) ✓

### Verification Result: PASSED
"""
    path = DEMO_RUN_DIR / "final" / "verification.md"
    ensure_dir(path.parent)
    with open(path, "w") as f:
        f.write(content)
    print(f"Created: {path}")


def create_verify_json() -> None:
    """Create verify.json."""
    data = {
        "stage": "audit",
        "status": "completed",
        "verified_claims_count": 3,
        "single_source_claims_count": 3,
        "conflicts_count": 0,
        "total_paragraphs": 3,
        "paragraph_without_citation_count": 0,
        "paragraph_end_citation_passed": True,
        "paragraphs_jsonl_cite_ids_passed": True,
        "citations_found": 3,
        "passed": True
    }
    path = DEMO_RUN_DIR / "evidence" / "verify.json"
    ensure_dir(path.parent)
    with open(path, "w") as f:
        json.dump(data, f, indent=2)
    print(f"Created: {path}")


def create_citations_json() -> None:
    """Create citations.json."""
    data = [
        {
            "cid": "C001",
            "url": "https://example.com/climate-agriculture-impacts",
            "title": "Climate Change Impacts on Agriculture",
            "locator": "https://example.com/climate-agriculture-impacts",
            "fetched_at": "2026-02-26T21:26:58.536923",
            "quote_hash": None,
            "local_path": None
        },
        {
            "cid": "C002",
            "url": "https://example.com/food-security-challenges",
            "title": "Global Food Security Challenges",
            "locator": "https://example.com/food-security-challenges",
            "fetched_at": "2026-02-26T21:27:00.123456",
            "quote_hash": None,
            "local_path": None
        },
        {
            "cid": "C003",
            "url": "https://example.com/adaptation-strategies",
            "title": "Agricultural Adaptation Strategies",
            "locator": "https://example.com/adaptation-strategies",
            "fetched_at": "2026-02-26T21:27:02.234567",
            "quote_hash": None,
            "local_path": None
        }
    ]
    path = DEMO_RUN_DIR / "evidence" / "citations.json"
    ensure_dir(path.parent)
    with open(path, "w") as f:
        json.dump(data, f, indent=2)
    print(f"Created: {path}")


def create_plan_json() -> None:
    """Create plan.json."""
    data = {
        "workers": 5,
        "depth": "medium",
        "budget": 10,
        "lang": "en",
        "plan": {
            "queries": ["climate change impact on agriculture"],
            "sources": ["web", "academic"],
            "estimated_sources": 50,
            "depth": "medium"
        }
    }
    path = DEMO_RUN_DIR / "logs" / "plan.json"
    ensure_dir(path.parent)
    with open(path, "w") as f:
        json.dump(data, f, indent=2)
    print(f"Created: {path}")


def create_pipeline_jsonl() -> None:
    """Create pipeline.jsonl."""
    timestamp = "2026-02-26T21:26:58"
    lines = [
        f'{{"timestamp": "{timestamp}.123456", "run_id": "demo_run", "stage": "intake", "status": "started", "details": {{}}}}',
        f'{{"timestamp": "{timestamp}.234567", "run_id": "demo_run", "stage": "intake", "status": "completed", "details": {{"success": true}}}}',
        f'{{"timestamp": "{timestamp}.345678", "run_id": "demo_run", "stage": "plan", "status": "started", "details": {{}}}}',
        f'{{"timestamp": "{timestamp}.456789", "run_id": "demo_run", "stage": "plan", "status": "completed", "details": {{"success": true}}}}',
    ]
    path = DEMO_RUN_DIR / "logs" / "pipeline.jsonl"
    ensure_dir(path.parent)
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Created: {path}")


def main():
    """Generate demo_run directory."""
    print("=" * 50)
    print("Deep Research - Demo Run Generator")
    print("=" * 50)
    print()

    # Create demo_run directory
    ensure_dir(DEMO_RUN_DIR)
    ensure_dir(DEMO_RUN_DIR / "drafts")
    ensure_dir(DEMO_RUN_DIR / "final")
    ensure_dir(DEMO_RUN_DIR / "evidence")
    ensure_dir(DEMO_RUN_DIR / "logs")

    print(f"Creating demo run at: {DEMO_RUN_DIR}")
    print()

    # Create all artifacts
    create_clarify_json()
    create_paragraphs_jsonl()
    create_report_md()
    create_verification_md()
    create_verify_json()
    create_citations_json()
    create_plan_json()
    create_pipeline_jsonl()

    print()
    print("=" * 50)
    print("Demo run created successfully!")
    print(f"Location: {DEMO_RUN_DIR}")
    print()
    print("To verify:")
    print(f"  ls -la {DEMO_RUN_DIR}")
    print()


if __name__ == "__main__":
    main()
